{"uuid":"ccc57075-de48-41a1-9fa2-e2b5bfd43e77","historyId":"9724623bc4ee232f92728d14a2072adc","fullName":"org.api.tests.AuthTest.forgotPasswordTest","labels":[{"name":"package","value":"org.api.tests.AuthTest"},{"name":"testClass","value":"org.api.tests.AuthTest"},{"name":"testMethod","value":"forgotPasswordTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"apiassured"},{"name":"subSuite","value":"org.api.tests.AuthTest"},{"name":"host","value":"Rangegowda"},{"name":"thread","value":"10068@Rangegowda.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Forgot Password"},{"name":"epic","value":"Authentication"},{"name":"feature","value":"Auth Service"},{"name":"severity","value":"normal"}],"links":[],"name":"Verify if forgot password API is working.","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [200] but found [500]","trace":"java.lang.AssertionError: expected [200] but found [500]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1590)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1431)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1395)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1441)\r\n\tat org.api.tests.AuthTest.forgotPasswordTest(AuthTest.java:98)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\r\n\tat org.testng.TestRunner.run(TestRunner.java:616)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"This test case verifies that the forgot password functionality works correctly.","steps":[],"attachments":[],"parameters":[],"start":1755236738586,"stop":1755236739557}